export const instructors = [
  {
    id: "ins-1",
    name: "Simon & Olivia Mia",
    role: "Web Design Mentors",
    tagline:
      "Helping beginners understand layout, hierarchy, spacing, typography, and responsive thinking with practical website-focused learning.",
    courses: ["Web Design"],
    language: "English & Arabic",
    level: "Beginner",
    duration: "1 Hour",
    teachingStyle: "Hands-on visual learning",
  },
  {
    id: "ins-2",
    name: "Mohamed Tarek",
    role: "Video Editing Instructor",
    tagline:
      "Focused on editing workflow, pacing, transitions, and stronger storytelling for creators, freelancers, and client work.",
    courses: ["Video editing", "Video Editing Part 2"],
    language: "Arabic",
    level: "Intermediate to Advanced",
    duration: "14 Hours + 11 Hours",
    teachingStyle: "Practical editing workflow",
  },
  {
    id: "ins-3",
    name: "Aymen singh",
    role: "Canva Designing Instructor",
    tagline:
      "Makes fast design creation easier for beginners through templates, branding basics, and content-ready visual execution.",
    courses: ["Canva Designing"],
    language: "Indian",
    level: "Beginner",
    duration: "10 Hours",
    teachingStyle: "Fast and accessible design practice",
  },
  {
    id: "ins-4",
    name: "Mark Shown",
    role: "Affiliate Marketing Instructor",
    tagline:
      "Teaches the foundations of affiliate systems, offer selection, promotion strategy, and conversion-focused growth.",
    courses: ["Affiliate Marketing"],
    language: "English",
    level: "Beginner",
    duration: "12 Hours",
    teachingStyle: "Strategy-first learning",
  },
  {
    id: "ins-5",
    name: "Mina Adel",
    role: "UI/UX Design Mentor",
    tagline:
      "Guides learners from UX thinking and user flows to wireframes, polished interfaces, and design system clarity.",
    courses: ["UI/UX Design"],
    language: "English",
    level: "Intermediate",
    duration: "20 Hours",
    teachingStyle: "Structured product thinking",
  },
  {
    id: "ins-6",
    name: "Yousef Samir",
    role: "Shopify Ecommerce Instructor",
    tagline:
      "Simplifies ecommerce setup through practical Shopify store building, theme editing, collections, and workflow basics.",
    courses: ["Shopify Ecommerce"],
    language: "Arabic",
    level: "Beginner",
    duration: "15 Hours",
    teachingStyle: "Store-building by practice",
  },
  {
    id: "ins-7",
    name: "Karim Nabil",
    role: "WordPress & DIVI Instructor",
    tagline:
      "Teaches no-code and low-code website building through WordPress and DIVI with a strong focus on usable client pages.",
    courses: ["WordPress & DIVI"],
    language: "Arabic",
    level: "Intermediate",
    duration: "17 Hours",
    teachingStyle: "Visual builder mastery",
  },
  {
    id: "ins-8",
    name: "Alaa Mostafa",
    role: "Fiverr Marketplace Mentor",
    tagline:
      "Helps beginners understand profile setup, gig writing, pricing logic, and stronger marketplace positioning.",
    courses: ["Fiverr Marketplace"],
    language: "Arabic",
    level: "Beginner",
    duration: "8 Hours",
    teachingStyle: "Freelancing entry roadmap",
  },
  {
    id: "ins-9",
    name: "Nour El Din",
    role: "Upwork Marketplace Mentor",
    tagline:
      "Focuses on profile optimization, proposal writing, job selection, and better client communication on Upwork.",
    courses: ["Upwork Marketplace"],
    language: "Arabic",
    level: "Beginner",
    duration: "9 Hours",
    teachingStyle: "Proposal-driven freelancing",
  },
  {
    id: "ins-10",
    name: "Salem Fathy",
    role: "Graphic Design Instructor",
    tagline:
      "Builds design confidence through composition, contrast, typography, and practical social and branding visuals.",
    courses: ["Graphic Design"],
    language: "Arabic",
    level: "Beginner",
    duration: "16 Hours / 9 Hours",
    teachingStyle: "Foundations with real design tasks",
  },
  {
    id: "ins-11",
    name: "Rahma Osama",
    role: "Digital Art & Illustration Mentor",
    tagline:
      "Introduces a creative digital art workflow through sketching, brush control, coloring, and expressive illustration.",
    courses: ["Digital Art & Illustration"],
    language: "English & Arabic",
    level: "Intermediate",
    duration: "13 Hours",
    teachingStyle: "Creative workflow development",
  },
  {
    id: "ins-12",
    name: "Tamer Wael",
    role: "3D Animation Instructor",
    tagline:
      "Explains motion, timing, and scene-based 3D animation processes for learners aiming to understand production flow.",
    courses: ["3D Animation"],
    language: "English",
    level: "Advanced",
    duration: "21 Hours",
    teachingStyle: "Pipeline-focused learning",
  },
  {
    id: "ins-13",
    name: "Ahmed Adel",
    role: "Microsoft Office Instructor",
    tagline:
      "Covers practical Word, Excel, and PowerPoint use cases for students, office work, and everyday productivity.",
    courses: ["Microsoft Office"],
    language: "Arabic",
    level: "Beginner",
    duration: "8 Hours",
    teachingStyle: "Practical office productivity",
  },
  {
    id: "ins-14",
    name: "Abdullah Kareem",
    role: "Quran Shikkha Instructor",
    tagline:
      "Supports learners through step-by-step recitation foundations with a gentle pace and clear progression.",
    courses: ["Quran Shikkha"],
    language: "Arabic & Bangla",
    level: "Beginner",
    duration: "11 Hours",
    teachingStyle: "Calm guided instruction",
  },
  {
    id: "ins-15",
    name: "Mahmoud Samy",
    role: "AI & ChatGPT Instructor",
    tagline:
      "Shows learners how to use AI and ChatGPT for prompts, productivity, ideation, and everyday work support.",
    courses: ["ChatGpt Ai"],
    language: "English & Arabic",
    level: "Beginner",
    duration: "7 Hours",
    teachingStyle: "Practical AI usage",
  },
  {
    id: "ins-16",
    name: "Ayman Ali",
    role: "Facebook Marketing Instructor",
    tagline:
      "Teaches campaign basics, targeting, content planning, and simple performance thinking for Facebook marketing.",
    courses: ["Facebook Marketing"],
    language: "Arabic",
    level: "Beginner",
    duration: "10 Hours",
    teachingStyle: "Campaign basics made simple",
  },
  {
    id: "ins-17",
    name: "Mostafa Adel",
    role: "SEO Instructor",
    tagline:
      "Focuses on keyword research, page structure, search visibility, and the foundations of practical SEO growth.",
    courses: ["SEO"],
    language: "English & Arabic",
    level: "Intermediate",
    duration: "12 Hours",
    teachingStyle: "Search-first optimization",
  },
  {
    id: "ins-18",
    name: "Nada Samir",
    role: "Email Marketing Instructor",
    tagline:
      "Helps learners build stronger email sequences, better audience targeting, and more effective campaign writing.",
    courses: ["Email marketing"],
    language: "Arabic",
    level: "Beginner",
    duration: "9 Hours",
    teachingStyle: "Conversion-focused email writing",
  },
  {
    id: "ins-19",
    name: "Hossam Nader",
    role: "Google Ads Instructor",
    tagline:
      "Explains keywords, ad copy, budget setup, campaign structure, and performance improvement for Google Ads.",
    courses: ["Google Ad"],
    language: "Arabic",
    level: "Intermediate",
    duration: "11 Hours",
    teachingStyle: "Paid ads with clarity",
  },
  {
    id: "ins-20",
    name: "Ali Fares",
    role: "Photography Instructor",
    tagline:
      "Introduces beginners to framing, lighting, composition, and stronger visual storytelling through photography basics.",
    courses: ["Photography"],
    language: "Arabic",
    level: "Beginner",
    duration: "8 Hours",
    teachingStyle: "Visual fundamentals in action",
  },
  {
    id: "ins-21",
    name: "Mariam Ashraf",
    role: "Drawing & Art Instructor",
    tagline:
      "Builds artistic confidence through sketching, form, observation, and composition practice for beginners.",
    courses: ["Drawing & Art"],
    language: "English & Arabic",
    level: "Beginner",
    duration: "10 Hours",
    teachingStyle: "Observation-led creativity",
  },
  {
    id: "ins-22",
    name: "Nourhan Adel",
    role: "Content Creation Mentor",
    tagline:
      "Teaches content planning, consistency, audience targeting, and better platform-ready content execution.",
    courses: ["Content Creation"],
    language: "Arabic",
    level: "Beginner",
    duration: "9 Hours",
    teachingStyle: "Content systems and consistency",
  },
  {
    id: "ins-23",
    name: "Yassin Hatem",
    role: "Ethical Hacking Instructor",
    tagline:
      "Introduces cybersecurity thinking, awareness, and foundational ethical hacking concepts in a safe learning context.",
    courses: ["Ethical Hacking"],
    language: "English",
    level: "Advanced",
    duration: "18 Hours",
    teachingStyle: "Security fundamentals with structure",
  },
];